In [153]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [154]:
df=pd.read_csv("../data/raw-data/raw_data.csv")

In [155]:
df.shape

(7043, 21)

In [156]:
df.duplicated().sum()

np.int64(0)

In [157]:

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [158]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [159]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [160]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [161]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [162]:
df.describe(include='str')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [163]:
df.drop("customerID",axis=1,inplace=True)

In [164]:
for col in df.columns: 
    print(f"{col}: {df[col].dtypes}, {df[col].nunique()} unique values")

gender: str, 2 unique values
SeniorCitizen: int64, 2 unique values
Partner: str, 2 unique values
Dependents: str, 2 unique values
tenure: int64, 73 unique values
PhoneService: str, 2 unique values
MultipleLines: str, 3 unique values
InternetService: str, 3 unique values
OnlineSecurity: str, 3 unique values
OnlineBackup: str, 3 unique values
DeviceProtection: str, 3 unique values
TechSupport: str, 3 unique values
StreamingTV: str, 3 unique values
StreamingMovies: str, 3 unique values
Contract: str, 3 unique values
PaperlessBilling: str, 2 unique values
PaymentMethod: str, 4 unique values
MonthlyCharges: float64, 1585 unique values
TotalCharges: str, 6531 unique values
Churn: str, 2 unique values

In [165]:
cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']
df[cols] = (
    df[cols]
    .astype('object')
    .replace({'Yes': 1, 'No': 0})
    .astype('Int64')
)

In [166]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df=df.dropna()
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [167]:
print(df.groupby("Churn")["tenure"].count())
print(df.groupby("Churn")["tenure"].mean())
print(df.groupby("Churn")["TotalCharges"].mean())
print(df.groupby("Churn")["MonthlyCharges"].mean())

Churn
0    5163
1    1869
Name: tenure, dtype: int64
Churn
0    37.650010
1    17.979133
Name: tenure, dtype: float64
Churn
0    2555.344141
1    1531.796094
Name: TotalCharges, dtype: float64
Churn
0    61.307408
1    74.441332
Name: MonthlyCharges, dtype: float64

In [168]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [169]:
pd.crosstab(
    df["PaymentMethod"],
    df["Churn"],
    normalize="index"
).mul(100).round(2)

Churn                          0      1
PaymentMethod
Bank transfer (automatic)  83.27  16.73
Credit card (automatic)    84.75  15.25
Electronic check           54.71  45.29
Mailed check               80.80  19.20

In [170]:
pd.crosstab(
    df["Contract"],
    df["Churn"],
    normalize="index"
).mul(100).round(2)

Churn               0      1
Contract
Month-to-month  57.29  42.71
One year        88.72  11.28
Two year        97.15   2.85

In [171]:
# Select numeric columns
num_df = df.select_dtypes(include='number')
# Calculate covariance matrix
cov_matrix = num_df.cov()
cov_matrix

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn
SeniorCitizen,0.136046,0.003125,-0.035540,0.141988,0.000915,0.028320,2.439951,8.562397e+01,0.024530
Partner,0.003125,0.249730,0.103430,4.684523,0.002717,-0.003427,1.470784,3.614364e+02,-0.033112
Dependents,-0.035540,0.103430,0.209425,1.835254,-0.000146,-0.024764,-1.546763,6.706746e+01,-0.032980
tenure,0.141988,4.684523,1.835254,602.469774,0.057149,0.058170,182.299526,4.595074e+04,-3.839186
PhoneService,0.000915,0.002717,-0.000146,0.057149,0.087362,0.002425,2.205644,7.571460e+01,0.001527
PaperlessBilling,0.028320,-0.003427,-0.024764,0.058170,0.002425,0.241438,5.202634,1.757920e+02,0.041560
MonthlyCharges,2.439951,1.470784,-1.546763,182.299526,2.205644,5.202634,905.165825,4.440133e+04,2.563362
TotalCharges,85.623972,361.436397,67.067462,45950.743236,75.714600,175.791980,44401.333073,5.138252e+06,-199.766978
Churn,0.024530,-0.033112,-0.032980,-3.839186,0.001527,0.041560,2.563362,-1.997670e+02,0.195171

In [173]:
df.to_csv("../data/processed-data/cleaned_data.csv", index=False)

Univariate Analysis — Initial Findings:

Tenure: The histogram appears U-shaped, subject to confirmation from the plot.
MonthlyCharges: The distribution does not appear fully normal.
TotalCharges: The distribution appears right-skewed.
Contract: Month-to-month contracts appear to be the most common.
Churn: 5,163 customers stayed, while 1,869 customers churned. This corresponds to approximately 73.4% non-churn and 26.6% churn.
Data quality: Missing values, duplicate records, data types, and unique values will be checked using a data-quality report.